### ISSUE TITLE
Can not Horse ride and the Distance of see a horse is to low.

### ISSUE THREAD

**Issue by Titoo8899** [tiffanyjager/horse-colors#1] opened 2019-08-30 21:01 UTC
Hi I have a Problem with the Horse. I can this not ride. 
I hope with this 11 Pictures can you say me what a Problem with the horses make.

Your mod with gentechnic horses work but I can this horses not ride. Please check your mod and this Picture with all my mods with what I play.

<img width="960" alt="Teil 1" src="https://user-images.githubusercontent.com/42325138/64050963-e251be00-cb79-11e9-833f-ccb80756d343.PNG">
<img width="960" alt="Teil 2" src="https://user-images.githubusercontent.com/42325138/64050964-e251be00-cb79-11e9-820e-75a3573dffeb.PNG">
<img width="960" alt="Teil 3" src="https://user-images.githubusercontent.com/42325138/64050965-e251be00-cb79-11e9-8d22-656ddae07c3b.PNG">
<img width="960" alt="Teil 4" src="https://user-images.githubusercontent.com/42325138/64050966-e251be00-cb79-11e9-95be-ace211ed2f37.PNG">
<img width="960" alt="Teil 5" src="https://user-images.githubusercontent.com/42325138/64050971-e7af0880-cb79-11e9-82a6-7324d71b9f82.PNG">
<img width="960" alt="Teil 6" src="https://user-images.githubusercontent.com/42325138/64050972-e8479f00-cb79-11e9-8298-c4d7dacd7f75.PNG">
<img width="960" alt="Teil 7" src="https://user-images.githubusercontent.com/42325138/64050973-e8479f00-cb79-11e9-94f7-b0c39cc8f521.PNG">
<img width="960" alt="Teil 8" src="https://user-images.githubusercontent.com/42325138/64050974-e8479f00-cb79-11e9-89d2-ebe88d1910c2.PNG">
<img width="960" alt="Teil 9" src="https://user-images.githubusercontent.com/42325138/64050975-e8479f00-cb79-11e9-84dc-25535ba29aa8.PNG">
<img width="960" alt="Teil 10" src="https://user-images.githubusercontent.com/42325138/64050976-ec73bc80-cb79-11e9-889d-7cf7878b37b5.PNG">
<img width="960" alt="Teil 11" src="https://user-images.githubusercontent.com/42325138/64050977-ed0c5300-cb79-11e9-8e33-dd791858d814.PNG">

**Comment by Titoo8899** [comment] 2019-08-30 21:04
Hi,
the other think is the distance of see a Horse is to low. Pleace show this Picture and I hope you find the answer.
![2019-08-30_22 30 50](https://user-images.githubusercontent.com/42325138/64051150-758af380-cb7a-11e9-9d9a-c3f93e8b6fe4.png)

**Comment by tiffanyjager** [comment] 2019-08-30 22:17
When trying to ride, did you right click with an empty hand? Untamed horses don't let you get on if you're holding something.

Does this still happen with no other mods?

**Comment by Titoo8899** [comment] 2019-08-31 16:56
Hi,
to the First Point. Then I click on a Horse to sit on this have I not item in my hand. And the other think with the no other mods make. The Problem work when I only your mod in the mod folder have, no other mods.

**Comment by tiffanyjager** [comment] 2020-04-01 20:17
Closing as cannot reproduce.

**Closed by tiffanyjager** 2020-04-01 20:17 UTC
Labels: bug
